[package]
name = "sycamore-wordle"
version = "0.1.0"
edition = "2024"

[dependencies]
sycamore = "0.9.1"

[dependencies.web-sys]
features = ["Location", "Storage", "HtmlInputElement", "HtmlElement", "HtmlButtonElement"]
version = "0.3.77"
